lobby_location:
  ==: org.bukkit.Location
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 90.0  # Поворот
  pitch: 0.0 # Наклон

test:
  start:
    world: maps
    x: 666.5
    y: 64.0
    z: 666.5
  finish:
    world: maps
    x: 228.5
    y: 70.0
    z: 1337.5
  score: 100.0
  checkpoints:
    - world: maps
      x: 999.5
      y: 65.0
      z: 69.5
    - world: maps
      x: 1488.5
      y: 66.0
      z: 0.5