name: CeyZelParkour
version: 1.1
author: CeyZe1
main: net.ceyzel.parkour.CeyZelParkour
api-version: 1.21
permissions:
  ceyzelparkour.admin:
    description: пенис
    default: op
commands:
  ceyzel:
    description: писька
    usage: /ceyzel <subcommand>
    permission: ceyzelparkour.use
  lobby:
    description: жопа
    usage: /lobby
    permission: ceyzelparkour.lobby
  kill:
    description: залупа
    usage: /kill
    permission: ceyzelparkour.kill
